[package]
name        = "home-urbit-orchestrator"
description = "The orchestrator is responsible for managing the lifecycle of Home-Urbit"
homepage    = "https://github.com/odyslam/home-urbit"
authors     = ["odysseas.eth"]
version     = "0.1.0"
edition     = "2021"
license     = "GPL-3.0-only"


[dependencies]
actix-web = "4"
actix-files = "0.6.0"
reqwest = { version = "0.11", features = ["json"] }
tracing = "0.1"
tracing-subscriber = "0.2"
